Update 2017-03-24-sequence-labeling-on-a-structured-data.md
innodatalabs/innodatalabs.github.io pull request #2
Opened 2017-03-28 20:35 UTC by mkroutikov

2017-03-28 20:36 UTC, mkroutikov commented
@pythonner please have a look

2017-03-28 20:46 UTC, mkroutikov commented
Some comments not addressed in the changes:

>> We can hope that given a lot of data system can eventually learn that order of attributes does not matter 
>> and that
>>`cinqui&#232;me` represents the same word as `cinquième`. But it is obviously a huge and artificial  
>>complication.

>IS THIS A REAL PROBLEM?? I DON'T THINK SO. PARSING XML MAKES THESE CHARACTERS EQUIVALENT...

Yes, it is. In REFTAG I see &dquot; and similar garbage all the time. We can not control the way user serializes XML. Normalizing by parsing ans saving using utf-8 will loose connection to the input document.

> IOB REPRESENTATION ENCODES CLASS, NOT FEATURES. THIS EXAMPLE IS MISLEADING. So yes: using 
> attributes for doc and chapter is absolutely a good idea. Features would be some sort of feature vector 
> beside IOB, however.
Why not IOB for features? I agree, it may look confusing. But IOB was invented exactly for the purpose of
marking up the beginning of an interval and it seem to be well suited here. Example:
```
<b>Hello</b> <b>my friend</b>
```
Presence of `b` environment is a *feature*:
```
Hello    b
my       b
friend   b
```
Note that we lost the information that `b` restarts at token `my`. To put this information back we can
make two features `I-b` and `B-b`, in the spirit of `IOB`:
```
Hello   B-b
my       B-b
firend  I-b
```

2017-03-29 13:02 UTC, pythonner commented
Well, ok, I can see that in the 'pretend' approach, we don't parse XML characters and we therefore hope ampersand encoding can be learned.. but it will screw up word embedding lookup which is severe!

2017-03-29 13:03 UTC, pythonner requested changes

2017-03-29 13:03 UTC, pythonner commented on _posts/2017-03-24-sequence-labeling-on-a-structured-data.md
> +`cinqui&#232;me` represents the same word as `cinquième`. Alternatively, we may want to normalize the serialized text
This will cause major problem when using lexicon lookup or word embedding lookup as a feature.

2017-03-29 13:04 UTC, pythonner commented
> Why not IOB for features?

Really not. 

In IOB, you put the "chunk class" (author, organisation, city, country) not features.

Features a kept in a feature vector attached to the token.

2017-03-29 13:19 UTC, mkroutikov commented
>>Why not IOB for features?

>Really not.

>In IOB, you put the "chunk class" (author, organisation, city, country) not features.

>Features a kept in a feature vector attached to the token.

Nah, you missing my point. I can name my features any way I want. Event 'I-mike' is a valid feature. I am talking about features, and only features. Nowhere I say that columns in the sample input represent labels.

The IOB encoding is NOT label-specific. It is just a technique to mark up spans. If my feature is not local, but belongs to a span, I can use IOB to encode it. Why not? 

Check the "Hello my friend" example. If I choose `b` as a feature, then each token will have `b` feature
enabled. Alternatively I can use two features `B-b`  and `I-b` with the convention that `B-b` is attached 
only to the first token in the span. It is easy and straightforward to generate these features for every token. Now, tell me why can't I do this?

(Agree that IOB is so often used for labels that seeing the same technique applied to features may
be unexpected and confusing)

2017-03-29 13:40 UTC, merged

2017-04-03 10:52 UTC, mkroutikov reviewed
incorporated